package org.plantilla.be;
// Generated 20/02/2019 11:58:06 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private long idpersona;
     private String codSocio;
     private Long idTercero;
     private String agencia;
     private String nombreSocio;
     private String nroDoc;
     private String tipoPersona;
     private Date fechaIngreso;
     private Date fechaUltimoMov;
     private BigDecimal saldoAporte31dic;
     private BigDecimal saldoAporte18feb;
     private String sexo;
     private Date fechaNacimiento;
     private Integer edad;
     private String miembroMesa;
     private String miembroCargo;
     private Integer nroMesa;
     private Integer nroOrden;
     private String ordenAlfabetico;
     private String pabellon;
     private Integer piso;
     private Integer aula;

    public Persona() {
    }

	
    public Persona(long idpersona) {
        this.idpersona = idpersona;
    }
    public Persona(long idpersona, String codSocio, Long idTercero, String agencia, String nombreSocio, String nroDoc, String tipoPersona, Date fechaIngreso, Date fechaUltimoMov, BigDecimal saldoAporte31dic, BigDecimal saldoAporte18feb, String sexo, Date fechaNacimiento, Integer edad, String miembroMesa, String miembroCargo, Integer nroMesa, Integer nroOrden, String ordenAlfabetico, String pabellon, Integer piso, Integer aula) {
       this.idpersona = idpersona;
       this.codSocio = codSocio;
       this.idTercero = idTercero;
       this.agencia = agencia;
       this.nombreSocio = nombreSocio;
       this.nroDoc = nroDoc;
       this.tipoPersona = tipoPersona;
       this.fechaIngreso = fechaIngreso;
       this.fechaUltimoMov = fechaUltimoMov;
       this.saldoAporte31dic = saldoAporte31dic;
       this.saldoAporte18feb = saldoAporte18feb;
       this.sexo = sexo;
       this.fechaNacimiento = fechaNacimiento;
       this.edad = edad;
       this.miembroMesa = miembroMesa;
       this.miembroCargo = miembroCargo;
       this.nroMesa = nroMesa;
       this.nroOrden = nroOrden;
       this.ordenAlfabetico = ordenAlfabetico;
       this.pabellon = pabellon;
       this.piso = piso;
       this.aula = aula;
    }
   
    public long getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(long idpersona) {
        this.idpersona = idpersona;
    }
    public String getCodSocio() {
        return this.codSocio;
    }
    
    public void setCodSocio(String codSocio) {
        this.codSocio = codSocio;
    }
    public Long getIdTercero() {
        return this.idTercero;
    }
    
    public void setIdTercero(Long idTercero) {
        this.idTercero = idTercero;
    }
    public String getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }
    public String getNombreSocio() {
        return this.nombreSocio;
    }
    
    public void setNombreSocio(String nombreSocio) {
        this.nombreSocio = nombreSocio;
    }
    public String getNroDoc() {
        return this.nroDoc;
    }
    
    public void setNroDoc(String nroDoc) {
        this.nroDoc = nroDoc;
    }
    public String getTipoPersona() {
        return this.tipoPersona;
    }
    
    public void setTipoPersona(String tipoPersona) {
        this.tipoPersona = tipoPersona;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaUltimoMov() {
        return this.fechaUltimoMov;
    }
    
    public void setFechaUltimoMov(Date fechaUltimoMov) {
        this.fechaUltimoMov = fechaUltimoMov;
    }
    public BigDecimal getSaldoAporte31dic() {
        return this.saldoAporte31dic;
    }
    
    public void setSaldoAporte31dic(BigDecimal saldoAporte31dic) {
        this.saldoAporte31dic = saldoAporte31dic;
    }
    public BigDecimal getSaldoAporte18feb() {
        return this.saldoAporte18feb;
    }
    
    public void setSaldoAporte18feb(BigDecimal saldoAporte18feb) {
        this.saldoAporte18feb = saldoAporte18feb;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getMiembroMesa() {
        return this.miembroMesa;
    }
    
    public void setMiembroMesa(String miembroMesa) {
        this.miembroMesa = miembroMesa;
    }
    public String getMiembroCargo() {
        return this.miembroCargo;
    }
    
    public void setMiembroCargo(String miembroCargo) {
        this.miembroCargo = miembroCargo;
    }
    public Integer getNroMesa() {
        return this.nroMesa;
    }
    
    public void setNroMesa(Integer nroMesa) {
        this.nroMesa = nroMesa;
    }
    public Integer getNroOrden() {
        return this.nroOrden;
    }
    
    public void setNroOrden(Integer nroOrden) {
        this.nroOrden = nroOrden;
    }
    public String getOrdenAlfabetico() {
        return this.ordenAlfabetico;
    }
    
    public void setOrdenAlfabetico(String ordenAlfabetico) {
        this.ordenAlfabetico = ordenAlfabetico;
    }
    public String getPabellon() {
        return this.pabellon;
    }
    
    public void setPabellon(String pabellon) {
        this.pabellon = pabellon;
    }
    public Integer getPiso() {
        return this.piso;
    }
    
    public void setPiso(Integer piso) {
        this.piso = piso;
    }
    public Integer getAula() {
        return this.aula;
    }
    
    public void setAula(Integer aula) {
        this.aula = aula;
    }




}


