package org.plantilla.be;
// Generated 02/03/2018 06:04:54 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * Persona generated by hbm2java
 */
@Component
public class Persona  implements java.io.Serializable {


     private long idpersona;
     private String codSocio;
     private String agencia;
     private String socio;
     private Date fechaIngreso;
     private BigDecimal saldoDic;
     private BigDecimal saldoMar;
     private String sexo;
     private Date fechaNacimiento;
     private String nrodoc;
     private Integer edad;
     private String cargo;
     private String mesa;
     private String mesaVotacion;
     private String miembro;

    public Persona() {
    }

	
    public Persona(int idpersona) {
        this.idpersona = idpersona;
    }
    public Persona(int idpersona, String codSocio, String agencia, String socio, Date fechaIngreso, BigDecimal saldoDic, BigDecimal saldoMar, String sexo, Date fechaNacimiento, String nrodoc, Integer edad, String cargo, String mesa, String mesaVotacion) {
       this.idpersona = idpersona;
       this.codSocio = codSocio;
       this.agencia = agencia;
       this.socio = socio;
       this.fechaIngreso = fechaIngreso;
       this.saldoDic = saldoDic;
       this.saldoMar = saldoMar;
       this.sexo = sexo;
       this.fechaNacimiento = fechaNacimiento;
       this.nrodoc = nrodoc;
       this.edad = edad;
       this.cargo = cargo;
       this.mesa = mesa;
       this.mesaVotacion = mesaVotacion;
    }
   
    public long getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(long idpersona) {
        this.idpersona = idpersona;
    }
    public String getCodSocio() {
        return this.codSocio;
    }
    
    public void setCodSocio(String codSocio) {
        this.codSocio = codSocio;
    }
    public String getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }
    public String getSocio() {
        return this.socio;
    }
    
    public void setSocio(String socio) {
        this.socio = socio;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public BigDecimal getSaldoDic() {
        return this.saldoDic;
    }
    
    public void setSaldoDic(BigDecimal saldoDic) {
        this.saldoDic = saldoDic;
    }
    public BigDecimal getSaldoMar() {
        return this.saldoMar;
    }
    
    public void setSaldoMar(BigDecimal saldoMar) {
        this.saldoMar = saldoMar;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getNrodoc() {
        return this.nrodoc;
    }
    
    public void setNrodoc(String nrodoc) {
        this.nrodoc = nrodoc;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getMesa() {
        return this.mesa;
    }
    
    public void setMesa(String mesa) {
        this.mesa = mesa;
    }
    public String getMesaVotacion() {
        return this.mesaVotacion;
    }
    
    public void setMesaVotacion(String mesaVotacion) {
        this.mesaVotacion = mesaVotacion;
    }
//    
    public String getMiembro() {
        return this.miembro;
    }
    
    public void setMiembro(String miembro) {
        this.miembro = miembro;
    }




}


